version: '3.9'

services:
  order_processing_db:
    image: postgres:14.4-alpine
    container_name: order_processing_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - order_processing_postgres_data:/var/lib/postgres/data
    env_file: .env
    networks:
      - web_network

  order_processing:
    container_name: order_processing_app
    build: .
    depends_on:
      - order_processing_db
    command: sh -c "uv run alembic upgrade head && uv run python main.py"
    env_file: .env
    ports:
      - "8001:8001"
    networks:
      - web_network

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.11.8-management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
    networks:
      - web_network
    restart: always

volumes:
  order_processing_postgres_data:

networks:
  web_network:
    name: web_network
